### ISSUE TITLE
possible write decorator for making cancelable method?

### ISSUE THREAD

**Issue by MR-omid** [bitranox/wrapt-timeout-decorator#4]
* **I'm submitting a ... **
  - [x] support request

hi,
how to write decorator like this and use flag to terminate method ( and any loop inside ) instead of using timeout in multi thread application?

for example:
```
    def download_files(urls):  
        for url in urls:  
            if cancel_request:
                return
            http.download(url)
```

possible write this method and use decorator for terminate?

for example:

```
    @Cancelable
    def download_files(urls):  
        for url in urls:  
            http.download(url)
```
      
thanks for your helping :1st_place_medal:

**Comment by bitranox** [comment]
but this is exactly what the timeout decorator does ! It raises TimeoutError (or You can define another Exception to use) when the Time Limit You set is reached.
But for the snippet You gave, I would use urllib3, it supports timeouts and retry itself.
See: 
http://urllib3.readthedocs.io/en/latest/reference/urllib3.util.html

`
import urllib3
import urllib3.request
import urllib3.util
def save_url_to_file(s_url:str, s_file_save_pathname:str):
    """
    saves url to file

    :param s_url:
    :param s_file_save_pathname:
    :return:
    :raises:   urllib3.exceptions.HTTPError if not possible to download

    >>> import os
    >>> s_file_save_pathname='/home/user/test.download'
    >>> save_url_to_file('https://www.rotek.at/images/Homepage-header.png',s_file_save_pathname)
    >>> if os.path.getsize(s_file_save_pathname) >0: print('success')
    success

    >>> save_url_to_file('https://www.rotek.at/images/doesnotexistxyz',s_file_save_pathname) # doctest: +ELLIPSIS +NORMALIZE_WHITESPACE
    Traceback (most recent call last):
        ...
    urllib3.exceptions.HTTPError: URL https://www.rotek.at/images/doesnotexistxyz can not be downloaded


    """
    urllib3_retries = urllib3.util.retry.Retry(connect=5, read=2, redirect=5)
    urllib3_pool_man = urllib3.PoolManager(cert_reqs='CERT_REQUIRED', ca_certs=certifi.where(),retries=urllib3_retries)
    response = urllib3_pool_man.request('GET', s_url,preload_content=False)
    if response.status==200:
        with open(s_file_save_pathname, 'wb') as out:
            while True:
                data = response.read(10 * 1024)  # chunk size 10k (max. 200K , siehe https://stackoverflow.com/questions/28695448/whats-the-best-chunk-size-for-a-urllib2-urlopen-read
                if not data:
                    break
                out.write(data)
        response.release_conn()
        response.close()
    else:
        s_message = 'URL {s_url} can not be downloaded'.format(**locals())
        raise urllib3.exceptions.HTTPError(s_message)

`
